"""Change registered_at

Revision ID: f08da5f916ae
Revises: 2487dd1f255e
Create Date: 2023-07-18 14:16:16.362192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08da5f916ae'
down_revision = '2487dd1f255e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
